//blogs
GET  http://localhost:3003/api/blogs
###
GET  http://localhost:3003/api/blogs/66fc577153374a2cee425047
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
{
  "title": "Cong Home",
  "author": "Victor",
  "url": "https://blogs/4",
  "likes": 10
}
###
DELETE http://localhost:3003/api/blogs/66fc577153374a2cee425047
###

//users
GET  http://localhost:3003/api/users
###
GET http://localhost:3003/api/users/id
###
DELETE http://localhost:3003/api/users/id
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "rotich",
    "name": "Superuser",
    "password": "salainen"
}

###
//login
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "rot",
    "password": "salainen"
}